import type { IconName } from "@/components/Icon";
import { site } from "@/lib/site";

/** Conteúdo extraído do "Plano de Trabalho – Portfólio de Cursos Inova Nexel". */

export type Duracao = "curto" | "medio" | "longo";
export type Segmento = "publico" | "empresarial";

export type Curso = {
  id: string;
  titulo: string;
  duracao: Duracao;
  contexto?: string;
  importancia?: string;
  publico?: string;
};

export type Trilha = {
  id: string;
  titulo: string;
  segmento: Segmento;
  icon: IconName;
  destaque?: string;
  responsaveis?: string;
  cursos: Curso[];
};

export const duracoes: Record<Duracao, { label: string; horas: string; resumo: string }> = {
  curto: { label: "Curta duração", horas: "4 a 8 horas", resumo: "Conceitos introdutórios" },
  medio: { label: "Média duração", horas: "12 a 24 horas", resumo: "Conteúdo técnico e específico" },
  longo: { label: "Longa duração", horas: "40 a 80 horas", resumo: "Trilha completa de formação" },
};

export const segmentos: Record<Segmento, string> = {
  publico: "Gestão pública",
  empresarial: "Empresarial",
};

export const metodologia = [
  "Aulas práticas e aplicadas à realidade local",
  "Estudos de caso de prefeituras, câmaras e estados",
  "Modelos prontos: editais, projetos, fluxos e relatórios",
  "Oficinas mão na massa",
  "Certificação por carga horária",
];

type CursoInput = Omit<Curso, "id">;

function slug(s: string) {
  return s
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function c(duracao: Duracao, titulo: string, contexto?: string, importancia?: string, publico?: string): CursoInput {
  return { titulo, duracao, contexto, importancia, publico };
}

function trilha(t: Omit<Trilha, "cursos"> & { cursos: CursoInput[] }): Trilha {
  return { ...t, cursos: t.cursos.map((x) => ({ ...x, id: `${t.id}--${slug(x.titulo)}` })) };
}

export const trilhas: Trilha[] = [
  trilha({
    id: "gestao-publica-governanca",
    titulo: "Gestão Pública e Governança",
    segmento: "publico",
    icon: "building",
    cursos: [
      c("curto", "Introdução à Gestão Pública Moderna",
        "A Gestão Pública Moderna representa a evolução dos modelos tradicionais de administração pública, incorporando práticas de eficiência, planejamento estratégico, inovação, transparência e foco em resultados. Baseia-se em governança, accountability, gestão por indicadores e uso de tecnologias para melhoria dos serviços públicos.",
        "Permite que gestores e servidores compreendam as novas exigências da administração pública contemporânea, promovendo maior eficiência no uso dos recursos públicos, melhoria na prestação de serviços e fortalecimento da confiança da população nas instituições.",
        "Gestores públicos, vereadores, assessores parlamentares, servidores administrativos e profissionais que atuam ou desejam atuar na gestão pública."),
      c("curto", "Noções de Governança no Legislativo",
        "Conjunto de práticas, mecanismos e processos que orientam a atuação das Casas Legislativas, assegurando transparência, integridade, eficiência e alinhamento com o interesse público.",
        "Fortalece a credibilidade institucional, melhora a tomada de decisão e reduz riscos de irregularidades, além de garantir maior controle social e qualidade na produção legislativa.",
        "Vereadores, assessores legislativos, diretores administrativos, controladores internos e servidores das Casas Legislativas."),
      c("curto", "Controle Interno na Prática",
        "O controle interno é um sistema de procedimentos, normas e rotinas adotadas pela administração pública para garantir legalidade, eficiência, economicidade e transparência na gestão dos recursos públicos.",
        "Previne erros, fraudes e desperdícios, assegura conformidade com a legislação e contribui para uma gestão mais segura e eficiente, evitando responsabilizações futuras.",
        "Controladores internos, gestores, servidores administrativos, contadores e responsáveis por processos e rotinas administrativas."),
      c("curto", "Papel do Vereador na Fiscalização",
        "A função fiscalizadora é uma das principais atribuições do vereador, consistindo no acompanhamento, monitoramento e controle das ações do Poder Executivo municipal.",
        "Garante o uso adequado dos recursos públicos, fortalece a democracia e assegura que as políticas públicas atendam aos interesses da população.",
        "Vereadores, assessores parlamentares e equipes de gabinete."),
      c("medio", "Gestão Patrimonial na Administração Pública",
        "Conjunto de práticas voltadas ao controle, registro, conservação e utilização dos bens públicos, incluindo móveis, imóveis e ativos permanentes.",
        "Assegura a correta utilização dos bens públicos, evita perdas e irregularidades, melhora a transparência e contribui para a eficiência da gestão pública.",
        "Servidores responsáveis pelo patrimônio, gestores administrativos, contadores e equipes de controle interno."),
      c("medio", "Avaliação e Reavaliação de Bens Públicos",
        "Procedimentos técnicos para mensuração e atualização do valor dos bens públicos, conforme normas contábeis e patrimoniais.",
        "Garante a fidedignidade das informações contábeis, melhora a gestão patrimonial e atende às exigências legais e normativas dos órgãos de controle.",
        "Contadores, administradores, gestores patrimoniais, comissões de inventário e controle interno."),
      c("medio", "Contabilidade Pública Aplicada",
        "Área da contabilidade voltada ao registro, controle e demonstração dos atos e fatos da administração pública, conforme normas específicas do setor público.",
        "Permite o acompanhamento da execução orçamentária e financeira, garantindo transparência, controle e suporte à tomada de decisões.",
        "Contadores, servidores da área financeira, gestores públicos e profissionais que atuam com orçamento e finanças."),
      c("medio", "Controladoria e Auditoria no Setor Público",
        "A controladoria atua no planejamento, monitoramento e avaliação da gestão pública, enquanto a auditoria verifica a conformidade e a eficiência dos processos administrativos.",
        "Fortalece os mecanismos de controle, melhora a qualidade da gestão e reduz riscos de irregularidades e responsabilizações.",
        "Controladores, auditores, gestores, servidores de áreas estratégicas e equipes de compliance público."),
      c("longo", "Formação Completa em Gestão Pública Municipal",
        "Curso estruturado que integra os principais fundamentos da gestão pública municipal, abordando planejamento, execução, controle e avaliação das políticas públicas.",
        "Forma gestores mais preparados, capazes de atuar de forma estratégica, eficiente e alinhada às exigências legais e sociais.",
        "Prefeitos, vereadores, secretários, gestores públicos, servidores e profissionais que desejam atuar na gestão municipal."),
      c("longo", "Gestão Integrada: Patrimônio, Finanças e Controle",
        "Aborda a integração entre áreas essenciais da administração pública — patrimônio, finanças e controle — promovendo uma visão sistêmica da gestão.",
        "Evita falhas de comunicação entre setores, melhora a eficiência administrativa e fortalece a governança pública.",
        "Gestores públicos, controladores internos, contadores, diretores administrativos e servidores estratégicos."),
    ],
  }),
  trilha({
    id: "compras-publicas-inovacao",
    titulo: "Compras Públicas para Inovação e Novos Modelos de Contratação",
    segmento: "publico",
    icon: "gavel",
    cursos: [
      c("curto", "Introdução às Compras Públicas de Inovação",
        "Trata do uso do poder de compra do Estado como instrumento de estímulo à inovação, permitindo a contratação de soluções inovadoras, startups e tecnologias ainda em desenvolvimento.",
        "Transforma a administração pública em indutora de inovação, resolvendo problemas complexos com soluções mais eficientes e modernas.",
        "Gestores públicos, secretários, equipes de planejamento, setores de compras, inovação e jurídico."),
      c("curto", "Marco Legal da Inovação e Instrumentos do MCTI",
        "Aborda a Lei de Inovação (Lei nº 10.973/2004), o Marco Legal das Startups (LC nº 182/2021) e instrumentos que permitem parcerias entre governo, universidades e empresas.",
        "Amplia as possibilidades de contratação pública, permitindo maior flexibilidade jurídica e incentivo à inovação.",
        "Procuradores, assessores jurídicos, gestores públicos, servidores de planejamento e inovação."),
      c("curto", "Contratação de Soluções Tecnológicas no Setor Público",
        "Formas de contratar tecnologia e inovação no setor público, incluindo softwares, plataformas digitais, inteligência artificial e soluções GovTech.",
        "Permite modernizar a administração pública e melhorar a eficiência dos serviços prestados à população.",
        "Gestores públicos, equipes de TI, inovação, compras e jurídico."),
      c("curto", "Dispensa e Inexigibilidade Aplicadas à Inovação",
        "Explora hipóteses legais que permitem contratações diretas em cenários de inovação, especialmente quando há inviabilidade de competição ou soluções exclusivas.",
        "Dá segurança jurídica para decisões mais ágeis e estratégicas, evitando entraves burocráticos desnecessários.",
        "Procuradores, controladores, gestores públicos, comissões de contratação e equipes jurídicas."),
      c("medio", "Sandbox Regulatório no Setor Público",
        "Ambiente controlado que permite testar soluções inovadoras com flexibilização regulatória, reduzindo riscos e incentivando a experimentação.",
        "Permite inovação com segurança, possibilitando testes antes da implementação em larga escala.",
        "Gestores públicos, reguladores, jurídico, equipes de inovação e planejamento."),
      c("medio", "Encomenda Tecnológica (ETEC) na Prática",
        "Instrumento previsto no Marco Legal da Inovação que permite ao poder público contratar o desenvolvimento de uma solução ainda inexistente no mercado.",
        "Resolve problemas complexos da administração pública com soluções sob medida, estimulando pesquisa e desenvolvimento.",
        "Gestores públicos, universidades, centros de pesquisa, jurídico e equipes de inovação."),
      c("medio", "Startups e GovTechs: Como o Poder Público Pode Contratar",
        "Modelos de contratação de startups com base no Marco Legal das Startups, incluindo o CPSI (Contrato Público para Solução Inovadora).",
        "Aproxima o setor público do ecossistema de inovação, trazendo soluções mais rápidas e eficientes.",
        "Gestores públicos, equipes de inovação, compras, jurídico e planejamento."),
      c("medio", "Gestão de Riscos em Contratações Inovadoras",
        "Identificação, análise e mitigação de riscos em contratações não tradicionais, especialmente em inovação.",
        "Garante segurança jurídica e administrativa, reduzindo resistências internas à inovação.",
        "Controladores internos, gestores, jurídico, auditores e equipes de governança."),
      c("medio", "Laboratórios de Inovação no Setor Público (GovLabs)",
        "Criação e gestão de laboratórios de inovação dentro do governo para desenvolvimento e teste de soluções públicas.",
        "Estimula a cultura de inovação, melhora processos internos e gera soluções mais eficazes.",
        "Gestores públicos, lideranças institucionais, equipes de inovação e planejamento."),
      c("longo", "Formação Completa em Compras Públicas para Inovação",
        "Curso estruturado que integra aspectos jurídicos, técnicos e estratégicos das contratações públicas voltadas à inovação.",
        "Forma profissionais preparados para implementar inovação no setor público com segurança jurídica e eficiência.",
        "Gestores públicos, procuradores, controladores, equipes de compras, inovação e planejamento."),
    ],
  }),
  trilha({
    id: "inovacao-desenvolvimento-economico",
    titulo: "Inovação, Empreendedorismo e Desenvolvimento Econômico",
    segmento: "publico",
    icon: "chart",
    cursos: [
      c("curto", "O Papel do Legislativo na Inovação",
        "Atuação do Poder Legislativo como agente estratégico na promoção da inovação, por meio de leis, incentivos, políticas públicas e marcos regulatórios que favoreçam o desenvolvimento tecnológico, o empreendedorismo e os ambientes de inovação.",
        "Permite que o Legislativo deixe de ser apenas reativo e passe a atuar como protagonista no desenvolvimento econômico local, criando condições para atração de empresas, startups e investimentos.",
        "Vereadores, assessores parlamentares, consultores legislativos e servidores envolvidos na elaboração de políticas públicas e projetos de lei."),
      c("curto", "Cidades Inteligentes na Prática",
        "Cidades Inteligentes utilizam tecnologia, dados e inovação para melhorar a qualidade de vida da população, a eficiência dos serviços públicos e a sustentabilidade urbana.",
        "Ajuda gestores a implementarem soluções práticas em mobilidade, segurança, saúde, educação e gestão urbana, utilizando recursos tecnológicos de forma estratégica.",
        "Gestores públicos, vereadores, secretários municipais, técnicos de planejamento e servidores das áreas urbanas e tecnológicas."),
      c("curto", "Introdução à Economia da Inovação",
        "Como a inovação impacta o desenvolvimento econômico, a competitividade e a geração de emprego e renda, com base em economia do conhecimento, capital intelectual e ecossistemas de inovação.",
        "Permite compreender como municípios podem crescer economicamente por meio da inovação, indo além de modelos baseados apenas em recursos naturais.",
        "Gestores públicos, economistas, planejadores, vereadores e profissionais envolvidos com desenvolvimento econômico."),
      c("medio", "Políticas Públicas de Inovação Municipal",
        "Estruturação de políticas públicas voltadas à inovação, incluindo leis de inovação, incentivos fiscais, programas de apoio a startups e parcerias com universidades e setor privado.",
        "Possibilita transformar o município em um ambiente favorável à inovação, estimulando novos negócios e fortalecendo a economia local.",
        "Gestores públicos, vereadores, secretários, técnicos de planejamento e agentes de desenvolvimento."),
      c("medio", "Ecossistemas de Startups e Desenvolvimento Local",
        "Funcionamento dos ecossistemas de inovação, compostos por startups, universidades, governo, investidores e instituições de apoio.",
        "Ajuda o poder público a fomentar e participar ativamente desses ecossistemas, promovendo desenvolvimento econômico sustentável.",
        "Gestores públicos, agentes de inovação, empreendedores públicos, servidores e lideranças institucionais."),
      c("medio", "Como Atrair Investimentos para Municípios",
        "Estratégias e mecanismos para captação de investimentos públicos e privados, incluindo incentivos, estruturação de projetos e melhoria do ambiente de negócios.",
        "Fundamental para geração de emprego, aumento da arrecadação e fortalecimento da economia local.",
        "Prefeitos, vereadores, secretários, agentes de desenvolvimento, técnicos e gestores públicos."),
      c("longo", "Planejamento Estratégico para Desenvolvimento Econômico",
        "Construção de estratégias de longo prazo para o crescimento econômico municipal, com base em diagnóstico, definição de prioridades e implementação de ações estruturadas.",
        "Evita ações isoladas e descoordenadas, promovendo crescimento sustentável e alinhado às vocações locais.",
        "Gestores públicos, secretários, planejadores, economistas e lideranças institucionais."),
      c("longo", "Criação de Ambientes de Inovação",
        "Concepção, implantação e gestão de ambientes de inovação, como hubs, incubadoras, aceleradoras e parques tecnológicos.",
        "Esses ambientes são fundamentais para fomentar o empreendedorismo, atrair talentos e desenvolver novas soluções para o mercado e o setor público.",
        "Gestores públicos, universidades, lideranças institucionais, agentes de inovação e desenvolvedores de políticas públicas."),
    ],
  }),
  trilha({
    id: "financas-orcamento",
    titulo: "Finanças, Orçamento e Responsabilidade Fiscal",
    segmento: "publico",
    icon: "funding",
    cursos: [
      c("curto", "Noções de Orçamento Público",
        "O orçamento público é o instrumento de planejamento que estima receitas e fixa despesas do governo para determinado período, estruturado por meio de leis como o PPA, a LDO e a LOA.",
        "Permite o planejamento e a organização dos gastos públicos, garantindo que os recursos sejam aplicados de forma eficiente e alinhada às prioridades da gestão.",
        "Vereadores, assessores parlamentares, gestores públicos e servidores que atuam ou desejam compreender a estrutura orçamentária."),
      c("curto", "LRF na Prática",
        "A Lei de Responsabilidade Fiscal (LC nº 101/2000) estabelece normas para a gestão fiscal responsável, impondo limites e condições para despesas, endividamento e transparência.",
        "Evita desequilíbrios financeiros, garante responsabilidade na gestão dos recursos públicos e protege gestores contra irregularidades e sanções legais.",
        "Gestores públicos, contadores, controladores internos, vereadores e servidores das áreas financeira e administrativa."),
      c("medio", "Planejamento Orçamentário Municipal",
        "Elaboração e integração dos instrumentos de planejamento governamental (PPA, LDO e LOA), alinhando metas, programas e ações às necessidades da população.",
        "Garante que o município tenha um planejamento estruturado, evitando improvisos e promovendo maior eficiência na execução das políticas públicas.",
        "Secretários, gestores públicos, planejadores, contadores e servidores envolvidos com orçamento e planejamento."),
      c("medio", "Gestão Financeira no Setor Público",
        "Controle, execução e acompanhamento das receitas e despesas públicas, incluindo fluxo de caixa, execução financeira e gestão de recursos.",
        "Assegura equilíbrio financeiro, melhor alocação de recursos e maior eficiência na execução orçamentária.",
        "Gestores financeiros, contadores, tesoureiros, ordenadores de despesa e servidores da área financeira."),
      c("longo", "Formação em Gestão Fiscal e Orçamentária",
        "Curso completo que integra orçamento, finanças e responsabilidade fiscal, abordando desde o planejamento até a execução e o controle.",
        "Forma profissionais capacitados para atuar de forma estratégica e técnica na gestão fiscal, reduzindo riscos e aumentando a eficiência administrativa.",
        "Gestores públicos, contadores, economistas, controladores internos e servidores da área financeira."),
    ],
  }),
  trilha({
    id: "comunicacao-posicionamento",
    titulo: "Vendas, Comunicação e Posicionamento para o Setor Público",
    segmento: "publico",
    icon: "users",
    cursos: [
      c("curto", "Comunicação Institucional Eficaz",
        "Estratégias e práticas utilizadas pelos órgãos públicos para se comunicar com clareza, transparência e eficiência com a população, a imprensa e demais instituições.",
        "Melhora a relação entre o poder público e a sociedade, fortalece a imagem institucional e evita ruídos que podem gerar crises ou desgaste político.",
        "Vereadores, assessores parlamentares, equipes de comunicação, gestores públicos e servidores que atuam no atendimento ao público."),
      c("curto", "Oratória para Agentes Públicos",
        "Técnicas de comunicação verbal, expressão corporal, argumentação e estruturação de discursos no ambiente público e institucional.",
        "Permite que agentes públicos se comuniquem com mais clareza, segurança e persuasão, seja em plenário, reuniões, audiências públicas ou eventos.",
        "Vereadores, líderes políticos, gestores públicos, assessores e servidores que precisam se comunicar em público."),
      c("medio", "Técnicas de Persuasão e Negociação no Setor Público",
        "Métodos de negociação, construção de consenso e técnicas de persuasão adaptadas ao ambiente público, respeitando princípios éticos e institucionais.",
        "Essencial para aprovação de projetos, articulação política, mediação de conflitos e construção de soluções entre diferentes interesses.",
        "Vereadores, gestores públicos, líderes institucionais, assessores e servidores envolvidos em processos decisórios."),
      c("medio", "Marketing Institucional e Imagem Pública",
        "Construção e gestão da imagem de instituições públicas e agentes políticos, com foco em comunicação estratégica, posicionamento e relacionamento com a sociedade.",
        "Fortalece a reputação institucional, amplia a transparência e melhora a percepção pública das ações governamentais.",
        "Vereadores, assessores de comunicação, gestores públicos e equipes institucionais."),
      c("longo", "Posicionamento Estratégico para Lideranças Públicas",
        "Construção de posicionamento estratégico de lideranças no setor público, alinhando discurso, atuação e imagem à missão institucional e às demandas da sociedade.",
        "Fortalece a liderança, melhora a capacidade de influência e contribui para uma atuação mais consistente e eficaz no ambiente político e institucional.",
        "Vereadores, gestores públicos, lideranças políticas e agentes institucionais."),
    ],
  }),
  trilha({
    id: "turismo-desenvolvimento-regional",
    titulo: "Turismo, Desenvolvimento Regional e Políticas Públicas",
    segmento: "publico",
    icon: "target",
    cursos: [
      c("curto", "Potencial Turístico como Vetor Econômico",
        "O turismo como atividade econômica estratégica, capaz de gerar emprego, renda e dinamizar setores como comércio, serviços e cultura.",
        "Permite que gestores identifiquem e explorem as vocações locais, transformando o turismo em ferramenta de desenvolvimento econômico sustentável.",
        "Gestores públicos, vereadores, secretários, agentes de desenvolvimento, profissionais de turismo e planejamento."),
      c("curto", "Turismo e Geração de Renda Local",
        "Impacto direto do turismo na economia local, especialmente na geração de emprego, empreendedorismo e inclusão produtiva.",
        "Fortalece economias locais, especialmente em municípios menores, promovendo distribuição de renda e valorização da cultura regional.",
        "Gestores públicos, empreendedores locais, secretarias de turismo e desenvolvimento econômico, vereadores e agentes comunitários."),
      c("medio", "Planejamento do Turismo Municipal",
        "Estruturação do turismo no âmbito municipal por meio de diagnóstico, definição de estratégias, criação de planos e organização da governança do setor.",
        "Evita ações isoladas e desorganizadas, promovendo desenvolvimento turístico sustentável e alinhado às potencialidades locais.",
        "Secretários municipais, gestores públicos, técnicos de planejamento, conselhos de turismo e vereadores."),
      c("medio", "Elaboração de Políticas Públicas de Turismo",
        "Criação, implementação e avaliação de políticas públicas voltadas ao desenvolvimento do turismo, incluindo legislação, programas e incentivos.",
        "Permite institucionalizar o turismo como prioridade governamental, garantindo continuidade das ações e maior acesso a recursos e investimentos.",
        "Gestores públicos, vereadores, técnicos de planejamento, assessores e profissionais envolvidos com políticas públicas."),
      c("longo", "Desenvolvimento Regional Sustentável",
        "Estratégias integradas de desenvolvimento que consideram aspectos econômicos, sociais e ambientais, com foco na valorização das potencialidades regionais.",
        "Promove crescimento equilibrado, reduz desigualdades regionais e garante uso sustentável dos recursos naturais.",
        "Gestores públicos, planejadores, economistas, lideranças regionais e agentes de desenvolvimento."),
      c("longo", "Gestão Estratégica do Turismo",
        "Gestão do turismo como atividade estratégica, incluindo governança, monitoramento de resultados, indicadores e integração com outras políticas públicas.",
        "Permite profissionalizar o setor, aumentar a competitividade do destino e garantir melhores resultados econômicos e sociais.",
        "Gestores públicos, secretários de turismo, coordenadores, técnicos e profissionais da área."),
    ],
  }),
  trilha({
    id: "empreendedorismo-inovador",
    titulo: "Empreendedorismo Inovador e Ecossistemas de Inovação",
    segmento: "publico",
    icon: "target",
    cursos: [
      c("curto", "Fundamentos do Empreendedorismo Inovador",
        "Fundamentos do empreendedorismo inovador: identificação de oportunidades, resolução de problemas, criação de soluções e desenvolvimento de novos negócios.",
        "Desenvolve uma visão empreendedora orientada à inovação, estimulando soluções capazes de gerar valor econômico e social.",
        "Empreendedores, estudantes, pesquisadores, servidores públicos, gestores, profissionais liberais e interessados em inovação e novos negócios."),
      c("curto", "Da Ideia ao Negócio Inovador",
        "O processo de transformar uma ideia em oportunidade de negócio: identificação do problema, validação da solução, definição do público e estruturação inicial.",
        "Auxilia empreendedores a reduzir riscos e transformar ideias em soluções concretas, alinhadas às necessidades reais do mercado.",
        "Empreendedores, estudantes, pesquisadores, startups, profissionais liberais e interessados em desenvolver novos negócios."),
      c("curto", "Identificação de Problemas e Criação de Soluções Inovadoras",
        "Técnicas para identificar problemas relevantes, compreender necessidades dos usuários e desenvolver soluções inovadoras a partir de desafios reais.",
        "Garante que projetos de inovação sejam construídos a partir de problemas concretos, e não apenas de ideias ou tecnologias.",
        "Empreendedores, gestores, servidores públicos, estudantes, pesquisadores e profissionais envolvidos com inovação."),
      c("curto", "Design Thinking Aplicado à Inovação",
        "O Design Thinking como abordagem para compreender problemas, ouvir usuários, gerar ideias, desenvolver protótipos e testar soluções.",
        "Estrutura processos colaborativos de inovação com foco nas necessidades reais das pessoas e organizações.",
        "Gestores, empreendedores, servidores públicos, profissionais de inovação, estudantes e equipes de projetos."),
      c("curto", "Modelagem de Negócios Inovadores",
        "Ferramentas para estruturar modelos de negócios: proposta de valor, segmentos de clientes, canais, receitas, custos e principais recursos.",
        "Transforma uma ideia em um modelo de negócio estruturado e passível de validação.",
        "Empreendedores, startups, estudantes, pesquisadores, gestores e profissionais interessados em novos negócios."),
      c("curto", "Startups: Fundamentos e Estruturação",
        "O conceito de startup, suas características, modelos de crescimento, validação de mercado, inovação e principais desafios de estruturação.",
        "Amplia a compreensão sobre negócios inovadores e prepara participantes para atuar ou empreender em ambientes de inovação.",
        "Empreendedores, estudantes, pesquisadores, profissionais de tecnologia, gestores e interessados em startups."),
      c("curto", "Pitch e Apresentação de Projetos Inovadores",
        "Construção e apresentação de pitches para projetos, startups, negócios inovadores e iniciativas de inovação.",
        "Desenvolve a capacidade de comunicar uma proposta de forma clara, objetiva e estratégica para parceiros, investidores e instituições.",
        "Empreendedores, startups, pesquisadores, estudantes, gestores e equipes de inovação."),
      c("curto", "Ecossistemas Locais de Inovação",
        "Formação e funcionamento de ecossistemas de inovação, envolvendo governo, empresas, universidades, instituições de pesquisa, startups e sociedade.",
        "Mostra como diferentes atores podem atuar de forma integrada para promover desenvolvimento econômico e tecnológico.",
        "Gestores públicos, empresários, instituições de ensino, pesquisadores, empreendedores e profissionais de inovação."),
      c("curto", "Inovação Aberta",
        "O conceito de inovação aberta e os mecanismos de cooperação entre empresas, governo, universidades, startups e demais organizações.",
        "Amplia a capacidade de inovação por meio do compartilhamento de conhecimentos, tecnologias, desafios e oportunidades.",
        "Empresas, gestores públicos, startups, universidades, pesquisadores e profissionais de inovação."),
      c("curto", "Empreendedorismo Inovador no Setor Público",
        "Empreendedorismo aplicado ao setor público, com foco na identificação de problemas, criação de soluções e desenvolvimento de iniciativas inovadoras dentro da administração.",
        "Estimula servidores e gestores a desenvolverem soluções para problemas públicos de maneira estruturada e orientada a resultados.",
        "Servidores públicos, gestores, secretários, agentes políticos, equipes de inovação e profissionais da administração pública."),
      c("medio", "Desenvolvimento de Negócios Inovadores",
        "Aprofunda o desenvolvimento de negócios inovadores: identificação de oportunidades, validação, modelagem, estratégia, mercado e crescimento.",
        "Estrutura negócios com maior capacidade de geração de valor, sustentabilidade e crescimento.",
        "Empreendedores, startups, gestores, pesquisadores e profissionais envolvidos na criação e desenvolvimento de negócios."),
      c("medio", "Gestão de Ecossistemas de Inovação",
        "Estruturação, governança e gestão de ecossistemas locais de inovação, considerando seus diferentes atores, recursos e ambientes.",
        "Organiza os atores locais e cria condições para o desenvolvimento contínuo de inovação e empreendedorismo.",
        "Gestores públicos, instituições de ensino, empresários, pesquisadores, profissionais de inovação e organizações de apoio."),
      c("medio", "Inovação Aberta e Parcerias Estratégicas",
        "Aprofunda mecanismos de inovação aberta, cooperação institucional, parcerias estratégicas e desenvolvimento conjunto de soluções.",
        "Amplia recursos, conhecimentos e capacidades por meio da colaboração entre diferentes organizações.",
        "Gestores, empresários, startups, universidades, instituições públicas e profissionais de inovação."),
      c("longo", "Formação em Empreendedorismo Inovador",
        "Programa completo para criação, estruturação e gestão de negócios inovadores, contemplando ideação, validação, modelagem, estratégia, mercado e crescimento.",
        "Formação integrada para quem quer transformar ideias e oportunidades em negócios sustentáveis e inovadores.",
        "Empreendedores, estudantes, pesquisadores, profissionais, startups e interessados em desenvolver negócios inovadores."),
    ],
  }),
  trilha({
    id: "lei-inovacao-rondonia",
    titulo: "Nova Lei de Inovação de Rondônia",
    segmento: "publico",
    icon: "shield",
    destaque: "Novo",
    cursos: [
      c("curto", "Nova Lei de Inovação de Rondônia: O Que Mudou?",
        "Apresenta a Lei Complementar nº 1.343/2026 e suas principais disposições sobre ciência, tecnologia, inovação, empreendedorismo inovador e desenvolvimento do ecossistema de inovação de Rondônia.",
        "Permite que gestores, instituições e empreendedores compreendam o novo marco estadual e suas possibilidades de aplicação.",
        "Gestores públicos, servidores, agentes políticos, empreendedores, pesquisadores, instituições de ensino e profissionais de inovação."),
      c("curto", "Empreendedorismo Inovador em Rondônia",
        "Oportunidades de empreendedorismo inovador dentro do novo ambiente institucional de ciência, tecnologia e inovação de Rondônia.",
        "Estimula empreendedores e organizações a identificarem oportunidades de soluções e negócios inovadores no Estado.",
        "Empreendedores, startups, pesquisadores, estudantes, empresas, gestores públicos e instituições de apoio."),
      c("medio", "Lei de Inovação de Rondônia na Prática",
        "Aprofunda a aplicação prática da LC nº 1.343/2026: instrumentos, atores, ambientes, financiamento, empreendedorismo inovador e mecanismos de estímulo à inovação.",
        "Transforma o conhecimento sobre a legislação em possibilidades práticas para municípios, instituições e organizações.",
        "Gestores públicos, secretários, servidores, procuradores, assessores legislativos, empreendedores e profissionais de CT&I."),
      c("medio", "Oportunidades da Nova Lei de Inovação para os Municípios",
        "Possibilidades de atuação dos municípios a partir do novo marco estadual: políticas públicas, ambientes de inovação, parcerias, financiamento e desenvolvimento econômico.",
        "Ajuda municípios a estruturar iniciativas locais alinhadas ao ecossistema estadual de ciência, tecnologia e inovação.",
        "Prefeitos, vereadores, secretários, procuradores, servidores, assessores e gestores municipais."),
      c("medio", "Novo Ecossistema de Ciência, Tecnologia e Inovação de Rondônia",
        "Principais atores, instituições, ambientes e mecanismos de articulação do ecossistema de ciência, tecnologia e inovação de Rondônia.",
        "Mostra como governo, empresas, universidades, instituições de pesquisa e empreendedores podem atuar juntos no desenvolvimento do Estado.",
        "Gestores públicos, empreendedores, pesquisadores, instituições de ensino, empresas e profissionais de inovação."),
    ],
  }),
  trilha({
    id: "direito-inovacao-govtech",
    titulo: "Direito da Inovação e GovTech",
    segmento: "publico",
    icon: "gavel",
    cursos: [
      c("curto", "Introdução ao Direito da Inovação",
        "Principais conceitos jurídicos relacionados à inovação, ciência, tecnologia, empreendedorismo inovador e desenvolvimento tecnológico.",
        "Oferece segurança conceitual para quem atua na criação, contratação e implementação de soluções inovadoras.",
        "Advogados, gestores públicos, servidores, empreendedores, pesquisadores e profissionais de tecnologia e inovação."),
      c("curto", "Marco Legal da Ciência, Tecnologia e Inovação",
        "Principais instrumentos jurídicos brasileiros relacionados à ciência, tecnologia e inovação e sua aplicação prática.",
        "Apresenta os mecanismos jurídicos disponíveis para estimular pesquisa, desenvolvimento tecnológico e inovação.",
        "Advogados, gestores públicos, pesquisadores, servidores, empresas e profissionais de inovação."),
      c("curto", "Direito e GovTech",
        "A relação entre Direito, tecnologia e transformação digital do Estado, abordando soluções tecnológicas voltadas à administração pública.",
        "Aponta os principais desafios jurídicos na implementação de soluções GovTech.",
        "Advogados, gestores públicos, servidores, profissionais de tecnologia, startups e empresas GovTech."),
      c("medio", "Governança Jurídica da Inovação",
        "Estruturas jurídicas e institucionais para apoiar processos de inovação, considerando governança, riscos, contratos, responsabilidades e instrumentos legais.",
        "Reduz a insegurança jurídica e organiza os processos de inovação.",
        "Advogados, procuradores, gestores, servidores, assessores jurídicos e profissionais de inovação."),
      c("medio", "Direito da Inovação Aplicado ao Setor Público",
        "Aplicação prática do Direito da Inovação na administração pública: instrumentos jurídicos, parcerias, propriedade intelectual, contratação de soluções inovadoras e governança.",
        "Capacita profissionais para estruturar iniciativas de inovação com maior segurança jurídica e aderência ao ambiente público.",
        "Advogados, procuradores, gestores, servidores, assessores, agentes políticos e profissionais de inovação."),
      c("longo", "Formação em Direito da Inovação e GovTech",
        "Formação completa sobre os aspectos jurídicos, institucionais e tecnológicos relacionados à inovação e à transformação digital do Estado.",
        "Desenvolve competências para atuar na construção de políticas, contratos, projetos e soluções jurídicas voltadas à inovação pública.",
        "Advogados, gestores públicos, procuradores, servidores, agentes políticos, profissionais de tecnologia e especialistas em inovação."),
    ],
  }),
  trilha({
    id: "leis-municipais-inovacao",
    titulo: "Construção de Leis e Políticas Municipais de Inovação",
    segmento: "publico",
    icon: "mission",
    cursos: [
      c("curto", "Como Criar uma Política Municipal de Inovação",
        "Fundamentos para construir uma política municipal de inovação, considerando problemas locais, vocações econômicas, atores do ecossistema e objetivos estratégicos.",
        "Ajuda municípios a estruturar políticas de inovação alinhadas às suas características e necessidades.",
        "Prefeitos, vereadores, secretários, servidores, assessores legislativos, instituições de ensino e agentes do ecossistema de inovação."),
      c("medio", "Como Criar uma Lei Municipal de Inovação",
        "Metodologia para construção de leis municipais de inovação: diagnóstico do município, escuta do ecossistema, identificação de recursos, governança, escolha de instrumentos e elaboração legislativa.",
        "Permite que municípios desenvolvam uma legislação de inovação conectada à realidade local e estruturada para implementação.",
        "Prefeitos, vereadores, procuradores, assessores legislativos, secretários, servidores e profissionais de políticas públicas de inovação."),
      c("medio", "Construção de Leis Municipais de Inovação — Método INOVA NEXEL",
        "Metodologia própria, em etapas: diagnóstico, diálogo com o ecossistema, definição de prioridades, dimensionamento de recursos, desenho dos instrumentos, desenvolvimento jurídico e implementação.",
        "Transforma a construção da lei em um processo estruturado, participativo e conectado à capacidade institucional e financeira do município.",
        "Prefeitos, vereadores, secretários, procuradores, assessores legislativos, servidores, universidades, empresas, startups e demais atores do ecossistema local."),
      c("medio", "Governança de Ecossistemas Municipais de Inovação",
        "Modelos de governança para integrar governo, empresas, universidades, instituições de pesquisa, startups e sociedade civil em torno de objetivos comuns de inovação.",
        "Organiza responsabilidades, fortalece articulações e cria condições para a continuidade das políticas de inovação.",
        "Gestores públicos, agentes políticos, instituições de ensino, empresários, pesquisadores e profissionais de inovação."),
      c("longo", "Formação em Políticas Públicas e Direito da Inovação",
        "Integra políticas públicas, legislação, governança, ciência, tecnologia, empreendedorismo e inovação para formar profissionais capazes de estruturar iniciativas de inovação.",
        "Formação abrangente para elaboração, implementação e avaliação de políticas públicas de inovação.",
        "Gestores públicos, advogados, agentes políticos, servidores, pesquisadores, profissionais de inovação e especialistas em políticas públicas."),
    ],
  }),
  trilha({
    id: "govtech-transformacao-digital",
    titulo: "GovTech e Transformação Digital",
    segmento: "publico",
    icon: "digital",
    cursos: [
      c("curto", "Introdução ao GovTech",
        "O conceito de GovTech e o uso de tecnologia e inovação para solucionar problemas públicos e melhorar a prestação de serviços.",
        "Mostra como startups, empresas de tecnologia e governos podem atuar juntos na transformação da administração pública.",
        "Gestores públicos, servidores, empreendedores, startups, profissionais de tecnologia e agentes políticos."),
      c("curto", "Governo e Startups: Construindo Soluções para Problemas Públicos",
        "Possibilidades de cooperação entre governo e startups para identificação e desenvolvimento de soluções para desafios da administração pública.",
        "Estimula novas formas de relacionamento entre setor público e ecossistema empreendedor.",
        "Gestores, servidores, startups, empreendedores, empresas de tecnologia e profissionais de inovação."),
      c("curto", "Inteligência Artificial na Administração Pública",
        "Aplicações da inteligência artificial em processos, serviços e atividades da administração pública, considerando governança e uso responsável.",
        "Ajuda a identificar oportunidades de uso da tecnologia para aumentar a eficiência e melhorar os serviços públicos.",
        "Gestores públicos, servidores, profissionais de tecnologia, assessores e agentes políticos."),
      c("medio", "GovTech: Do Problema Público à Solução Tecnológica",
        "Identificação de problemas públicos, definição de requisitos, desenvolvimento de soluções tecnológicas e estruturação de projetos GovTech.",
        "Transforma desafios concretos da administração pública em projetos estruturados de inovação e transformação digital.",
        "Gestores públicos, servidores, profissionais de tecnologia, startups, empresas GovTech e equipes de inovação."),
      c("medio", "Transformação Digital Municipal",
        "Transformação digital de municípios envolvendo processos, serviços, tecnologia, dados, pessoas, governança e estratégia.",
        "Ajuda municípios a estruturar uma agenda de transformação digital conectada às necessidades da população.",
        "Prefeitos, secretários, gestores, servidores, equipes de tecnologia e profissionais de inovação."),
      c("longo", "Formação em GovTech e Transformação Digital no Setor Público",
        "Formação completa sobre inovação tecnológica no setor público: GovTech, transformação digital, dados, inteligência artificial, inovação aberta, serviços digitais e contratação de soluções tecnológicas.",
        "Desenvolve competências para planejar e implementar estratégias de transformação digital na administração pública.",
        "Gestores públicos, servidores, profissionais de tecnologia, agentes políticos, startups e equipes de inovação."),
    ],
  }),
  trilha({
    id: "atendimento-publico",
    titulo: "Atendimento Público de Alta Performance",
    segmento: "publico",
    icon: "users",
    cursos: [
      c("curto", "Atendimento Público de Alta Performance",
        "Competências para um atendimento público eficiente, humanizado e orientado ao cidadão: comunicação, escuta ativa, postura profissional, resolução de conflitos e experiência do usuário.",
        "Melhora a qualidade do atendimento, reduz conflitos e fortalece a relação entre cidadão e administração pública.",
        "Servidores públicos, recepcionistas, atendentes, equipes administrativas, gestores e profissionais que atuam diretamente com o cidadão."),
      c("curto", "Comunicação e Experiência do Cidadão no Serviço Público",
        "Técnicas de comunicação, linguagem clara, escuta ativa, empatia, atendimento presencial, telefônico e digital e gestão de situações difíceis.",
        "Melhora a comunicação entre servidores e cidadãos e proporciona uma experiência mais eficiente nos serviços públicos.",
        "Servidores, gestores, atendentes, equipes de atendimento e profissionais que atuam na prestação de serviços públicos."),
      c("medio", "Formação em Atendimento Público e Experiência do Cidadão",
        "Programa de formação em atendimento, comunicação, relacionamento, resolução de conflitos, acessibilidade, ética, linguagem clara e experiência do cidadão.",
        "Promove uma visão integrada do atendimento público e prepara equipes para serviços mais eficientes, acessíveis e orientados ao cidadão.",
        "Servidores públicos, gestores, equipes administrativas, atendentes, recepcionistas e profissionais da prestação de serviços públicos."),
    ],
  }),
  trilha({
    id: "tributacao-licitacoes",
    titulo: "Tributação, Licitações e Inovação",
    segmento: "publico",
    icon: "package",
    cursos: [
      c("curto", "Benefícios Fiscais à Inovação: ZFM, Lei do Bem e FINEP",
        "Principais mecanismos de incentivo à inovação, com destaque para a Zona Franca de Manaus, a Lei do Bem e os instrumentos de apoio da FINEP.",
        "Ajuda a identificar oportunidades de incentivo e financiamento para projetos de inovação.",
        "Empresários, empreendedores de tecnologia, contadores, gestores, advogados, pesquisadores e profissionais de inovação."),
      c("curto", "Lei do Bem na Prática",
        "Aplicação prática da Lei do Bem: principais requisitos, documentação e utilização por empresas que desenvolvem atividades de pesquisa, desenvolvimento e inovação.",
        "Ajuda empresas a compreenderem as possibilidades e requisitos do incentivo fiscal à inovação.",
        "Empresários, gestores, contadores, advogados, profissionais financeiros e empresas de tecnologia e inovação."),
      c("curto", "FINEP: Como Captar Recursos para Inovação",
        "Mecanismos de apoio e financiamento à inovação, com foco nos instrumentos da FINEP e na estruturação de projetos.",
        "Amplia a capacidade das organizações de identificar oportunidades de financiamento para projetos inovadores.",
        "Empresas, startups, pesquisadores, gestores, empreendedores e responsáveis por projetos de inovação."),
      c("curto", "Reforma Tributária para Empresas de Tecnologia",
        "Principais impactos da reforma tributária sobre empresas de tecnologia e inovação, considerando o período de transição e seus efeitos no setor.",
        "Permite que empresas e profissionais compreendam os impactos tributários e se preparem para as mudanças.",
        "Empresas de tecnologia, startups, empresários, contadores, advogados e gestores financeiros."),
      c("curto", "Reforma Tributária e Contratos Públicos",
        "Impactos da reforma tributária nas contratações públicas, incluindo composição de preços, custos, BDI e efeitos sobre o equilíbrio econômico-financeiro.",
        "Ajuda empresas e profissionais que atuam com contratos públicos a compreender os impactos tributários em suas operações.",
        "Fornecedores do poder público, gestores, contadores, advogados, profissionais de licitações e contratos e equipes financeiras."),
      c("curto", "Benefícios Fiscais e Precificação em Licitações",
        "A relação entre benefícios fiscais, formação de preços e participação de empresas em processos de contratação pública.",
        "Mostra como aspectos tributários influenciam a composição de preços e a competitividade em licitações.",
        "Empresários, contadores, advogados, gestores, profissionais de licitações e fornecedores do setor público."),
      c("medio", "Reforma Tributária, Inovação e Contratações Públicas",
        "Integra os impactos da reforma tributária, os benefícios fiscais à inovação e os efeitos sobre contratos públicos, incluindo preços, BDI, planilhas de custos e equilíbrio econômico-financeiro.",
        "Visão integrada dos aspectos tributários e contratuais que impactam empresas inovadoras e fornecedoras do poder público.",
        "Empresários, contadores, advogados, gestores, profissionais de licitações, empresas de tecnologia e organizações que contratam com o poder público."),
      c("longo", "Benefícios Fiscais, Inovação e Contratações Públicas: Formação Estratégica",
        "Formação integrada sobre benefícios fiscais, inovação, reforma tributária, formação de preços e contratação pública.",
        "Visão estratégica para organizações que precisam conciliar inovação, tributação, competitividade e participação em contratos públicos.",
        "Empresários, gestores, contadores, advogados, profissionais financeiros, empresas de tecnologia e especialistas em licitações e contratos."),
    ],
  }),
  trilha({
    id: "politicas-publicas-inovacao",
    titulo: "Políticas Públicas de Inovação",
    segmento: "publico",
    icon: "eye",
    cursos: [
      c("curto", "Introdução às Políticas Públicas de Inovação",
        "Fundamentos das políticas públicas de inovação e sua relação com desenvolvimento econômico, tecnológico, social e regional.",
        "Mostra como governos podem utilizar políticas públicas para estimular inovação e desenvolvimento.",
        "Gestores públicos, servidores, agentes políticos, pesquisadores, empreendedores e profissionais de inovação."),
      c("curto", "Direito e Políticas Públicas de Inovação",
        "A relação entre legislação, políticas públicas e instrumentos de estímulo à ciência, tecnologia e inovação.",
        "Ajuda gestores a compreenderem o papel do Direito na criação e implementação de políticas públicas de inovação.",
        "Advogados, gestores, servidores, agentes políticos, pesquisadores e profissionais de políticas públicas."),
      c("curto", "Indicadores e Avaliação de Políticas de Inovação",
        "Indicadores e mecanismos de monitoramento para acompanhar resultados de programas e políticas públicas de inovação.",
        "Permite avaliar resultados, identificar melhorias e orientar decisões baseadas em evidências.",
        "Gestores públicos, servidores, pesquisadores, profissionais de planejamento e equipes de inovação."),
      c("medio", "Estruturação de Políticas Públicas Municipais de Inovação",
        "Diagnóstico, planejamento, definição de objetivos, governança, instrumentos, recursos, implementação e avaliação de políticas municipais de inovação.",
        "Ajuda municípios a transformar inovação em uma política pública estruturada e permanente.",
        "Prefeitos, vereadores, secretários, servidores, assessores e profissionais de planejamento e inovação pública."),
      c("medio", "Planejamento e Implementação de Estratégias Municipais de Inovação",
        "Ferramentas para construir e implementar estratégias municipais de inovação alinhadas às características econômicas, sociais e institucionais do município.",
        "Transforma objetivos de inovação em programas, projetos, ações e indicadores de acompanhamento.",
        "Gestores públicos, secretários, servidores, agentes políticos e equipes de planejamento."),
      c("longo", "Formação em Políticas Públicas e Inovação",
        "Formação integrada sobre diagnóstico, formulação, legislação, governança, implementação, monitoramento e avaliação de políticas públicas de inovação.",
        "Desenvolve profissionais capazes de atuar de forma estratégica na construção e execução de políticas de inovação.",
        "Gestores públicos, servidores, agentes políticos, pesquisadores, advogados e profissionais de inovação."),
    ],
  }),

  /* ---------- Capacitação empresarial ---------- */
  trilha({
    id: "marketing-posicionamento",
    titulo: "Marketing e Posicionamento de Negócios",
    segmento: "empresarial",
    icon: "target",
    responsaveis: "Peterson Marães e especialista em vendas",
    cursos: [
      c("curto", "Fundamentos de Marketing para Pequenos Negócios"),
      c("curto", "Posicionamento de Marca na Prática"),
      c("curto", "Redes Sociais que Vendem"),
      c("medio", "Marketing Digital para Empresas Locais"),
      c("medio", "Construção de Marca e Autoridade"),
      c("medio", "Estratégias de Conteúdo e Engajamento"),
      c("longo", "Formação em Marketing Estratégico para Negócios"),
      c("longo", "Posicionamento e Crescimento de Marca"),
    ],
  }),
  trilha({
    id: "vendas-negociacao",
    titulo: "Vendas, Negociação e Aumento de Faturamento",
    segmento: "empresarial",
    icon: "chart",
    responsaveis: "Especialista em vendas",
    cursos: [
      c("curto", "Técnicas de Vendas para Iniciantes"),
      c("curto", "Atendimento que Converte"),
      c("curto", "Erros que Estão Travando suas Vendas"),
      c("medio", "Funil de Vendas na Prática"),
      c("medio", "Técnicas de Persuasão e Fechamento"),
      c("medio", "Vendas Consultivas"),
      c("longo", "Formação em Vendas de Alta Performance"),
      c("longo", "Estruturação de Processo Comercial"),
    ],
  }),
  trilha({
    id: "gestao-financeira-precificacao",
    titulo: "Gestão Financeira e Precificação",
    segmento: "empresarial",
    icon: "funding",
    responsaveis: "Contadora e economista",
    cursos: [
      c("curto", "Noções de Finanças para Empreendedores"),
      c("curto", "Erros Financeiros que Quebram Empresas"),
      c("medio", "Formação de Preço de Venda"),
      c("medio", "Controle de Caixa e Fluxo Financeiro"),
      c("longo", "Gestão Financeira Completa para Pequenos Negócios"),
      c("longo", "Estratégia Financeira para Crescimento"),
    ],
  }),
  trilha({
    id: "food-service",
    titulo: "Food Service, Delivery e Engenharia de Cardápio",
    segmento: "empresarial",
    icon: "box",
    destaque: "Premium",
    responsaveis: "Peterson Marães (marketing e engenharia de cardápio), contadora, economista e especialista em vendas",
    cursos: [
      c("curto", "Introdução ao Food Business Lucrativo",
        "Visão geral do mercado de alimentação, comportamento do consumidor e modelos de negócio (restaurante, delivery, dark kitchen).",
        "Ajuda o empresário a entender como estruturar um negócio sustentável e competitivo.",
        "Donos de restaurantes, lanchonetes, delivery e empreendedores iniciantes."),
      c("medio", "Engenharia de Cardápio na Prática",
        "Metodologia que analisa o desempenho dos pratos com base em popularidade e margem de lucro.",
        "Permite identificar quais produtos dão lucro e quais estão prejudicando o negócio.",
        "Restaurantes, bares, hamburguerias, pizzarias e delivery."),
      c("medio", "Precificação Estratégica para Food Service",
        "Definição correta de preços com base em custos, margem, mercado e posicionamento.",
        "Evita prejuízo oculto e aumenta a lucratividade sem necessariamente aumentar as vendas.",
        "Empresários do setor alimentício e gestores financeiros."),
      c("medio", "Gestão Financeira para Restaurantes e Delivery",
        "Controle de custos, CMV (Custo de Mercadoria Vendida), fluxo de caixa e indicadores.",
        "Um dos principais fatores de sobrevivência no setor.",
        "Donos e gestores de negócios alimentícios."),
      c("medio", "Marketing para Restaurantes e Delivery",
        "Estratégias de marketing digital aplicadas ao food service: Instagram, iFood, tráfego e promoções.",
        "Aumenta visibilidade, pedidos e fidelização.",
        "Empresários e equipes de marketing."),
      c("medio", "Operação e Escala no Delivery",
        "Gestão de pedidos, logística, tempo de entrega e padronização.",
        "Melhora a experiência do cliente e aumenta a capacidade de crescimento.",
        "Negócios que trabalham com delivery."),
      c("longo", "Formação Completa em Gestão de Restaurantes e Delivery",
        "Programa integrado com marketing, vendas, financeiro e engenharia de cardápio.",
        "Transforma o negócio em uma operação profissional e lucrativa.",
        "Empresários que querem estruturar ou escalar seus negócios."),
    ],
  }),
];

export const totalCursos = trilhas.reduce((n, t) => n + t.cursos.length, 0);

/** Link do WhatsApp com a mensagem já preenchida com o curso escolhido. */
export function whatsappCurso(curso?: Curso, trilha?: Trilha) {
  const texto = curso
    ? `Olá, Inova Nexel! Tenho interesse no curso "${curso.titulo}" (trilha ${trilha?.titulo}). Pode me passar as próximas turmas e como me inscrever?`
    : "Olá, Inova Nexel! Tenho interesse nos cursos de capacitação. Pode me ajudar a escolher uma trilha?";
  return `${site.whatsappHref}?text=${encodeURIComponent(texto)}`;
}
